blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),

    path('tag/<slug:tag_slug>/',views.post_list,name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
            views.post_detail,name='post_detail'),

]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib import admin
from django.urls import re_path,path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls',namespace='blog')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                     document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                     document_root=settings.MEDIA_ROOT)

oilblog/oilblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls',namespace='post'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oilblog/post/urls.py
from django.urls import path
from .views import IndexView,index,PostDetailView,CategoryView
app_name = 'post'

urlpatterns = [
    path('post', IndexView.as_view(), name='index'),
    path('', index, name='index'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('category/<str:cats>/', CategoryView, name='category'),
]

oilblog/post/models.py
from django.db.models import Q
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.utils.text import slugify

from django.db.models.signals import pre_save, post_save
# from oilblog.utils import unique_slug_generator

User = get_user_model()

# Create your models here.

class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField()

    def __str__(self):
        return self.user.username

class Category(models.Model):
    title = models.CharField(max_length = 30)

    def __str__(self):
        return f"{self.title}"

class Comment(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    post = models.ForeignKey("Post", on_delete=models.CASCADE,
                            related_name='comments')
    approve_comment = models.BooleanField(default=False)
    def approve(self):
        self.approve_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'slug':self.slug})

    def __str__(self):
        return self.content



class PostQuerySet(models.query.QuerySet):
    def featured(self):
        return self.filter(featured=True)
        
class PostManager(models.Manager):

    def get_queryset(self):
        return PostQuerySet(self.model, using=self._db)
        
    def get_by_id(self, id):
        # return self.get_queryset().filter(id=id)  # Product.objects == self.get_queryset()
        qs = self.get_queryset().filter(id=id)
        if qs.count()==1:
            return qs.first()  # individual Object  
        return None

#     def search(self,query):
#         lookups = (Q(title__icontains=query)|
#                     Q(overview__icontains=query)|
#                     Q(author__icontains=query)
#         )
#         return self.get_queryset().filter(lookups).distinct()

class Post(models.Model):
    title = models.CharField(max_length=150)
    # slug = models.SlugField(max_length=150,blank=True,unique=True)
    overview = models.TextField()
    timestamp = models.DateTimeField(auto_now_add= True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    thumbnail = models.ImageField()
    incredient_pdf = models.ImageField(blank=True, null=True)
    categories = models.ManyToManyField(Category)
    featured = models.BooleanField()
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    objects = PostManager()

  
    def total_likes(self):
        return self.likes.all().count()

    def __str__(self):
        return str(self.pk)
    
    
    def get_absolute_url(self, **kwargs):
        return "/post/{pk}/".format(pk=self.pk)
        
        
    def get_category_count(self):
        return self.categories.all().count()

    def approve_comments(self):
        return self.comments.filter(approve_comment=True)

    def comment_count(self):
        return Comment.objects.filter(post=self).count()

# def post_pre_save_receiver(sender, instance, *args, **kwargs):
#     if not instance.slug:
#         instance.slug = unique_slug_generator(instance)

# pre_save.connect(post_pre_save_receiver, sender=Post)

oilblog/post/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,DetailView
from django.shortcuts import (render,
                                get_object_or_404,
                                redirect,
                                reverse,
                                Http404)


from django.core.paginator import Paginator 
from .models import Post, Category, Comment, Author
# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'


def index(request):
    posts = Post.objects.all()
    recent = Post.objects.order_by('-timestamp')[0:30]
    category = Category.objects.all()

    paginator = Paginator(posts, 9)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    
    context = {
        'object_list': posts,
        'recent':recent,
        'category': category,
    }

    return render(request,
                  'index.html',
                  context)

class PostDetailView(DetailView):
    template_name = 'posts/post-detail.html'
    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        instance = Post.objects.get_by_id(pk)
        if instance is None:
            raise Http404("Post doesn't exist")
        return instance

def CategoryView(request, cats):
    
    category_post = Post.objects.filter(categories__title=cats.replace('-',' '))
    context = {"category_post":category_post }
    return render(request, 'posts/category.html', context)

oilblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Oil4us</title>

     <!-- Font Awesome Icons -->
     <link rel="stylesheet" href="{% static './css/all.css' %}">
     <!-- --------- Owl-Carousel ------------------->
     <link rel="stylesheet" href="{% static './css/owl.carousel.min.css' %}">
     <link rel="stylesheet" href="{% static './css/owl.theme.default.min.css' %}">
     <!-- ------------ AOS Library ------------------------- -->
     <link rel="stylesheet" href="{% static './css/aos.css' %}">
     <!-- Custom Style   -->
     <link rel="stylesheet" href="{% static './css/Style.css' %}">

     <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v7.0"></script>
     
     {% block extrahead %}
     {% endblock %}
</head>

<body>
    
    <!-- ----------------------------  Navigation ---------------------------------------------- -->

    <nav class="nav">
        <div class="nav-menu flex-row">
            <div class="nav-brand" style="display:flex;flex-direction:row;">
                <a href="  " class="text-gray">
                    <img style="width:7rem;height:2rem;" src="/static/images/Oil4us(1).png"> 
                </a>
            </div>
            <div class="toggle-collapse">
                <div class="toggle-icons">
                    <i class="fas fa-bars"></i>
                </div>
            </div>
            <div>
                <ul class="nav-items">
                    <li class="nav-link">
                        <a href="  ">Home</a>
                    </li>
                    <li class="nav-link">
                        <a href="">Nutrition</a>
                    </li>
                    <li class="nav-link">
                        <a href="  ">Major Oil</a>
                    </li>
                    <li class="nav-link">
                        <a href="  ">Essential oil</a>
                    </li>
                    <li class="nav-link">
                        <a href="#">Contact Us</a>
                    </li>
                </ul>
            </div>
            <div class="social text-gray">
                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-youtube"></i></a>
            </div>
        </div>
    </nav>

    <!-- ------------x---------------  Navigation --------------------------x------------------- -->


{% block content %}
    
{% endblock content %}
    

    <!-- --------------------------- Footer ---------------------------------------- -->

    <footer class="footer">
        <div class="container">
            <div class="about-us" data-aos="fade-right" data-aos-delay="200">
                <h2>About us</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium quia atque nemo ad modi officiis
                    iure, autem nulla tenetur repellendus.</p>
            </div>
            <div class="newsletter" data-aos="fade-right" data-aos-delay="200">
                <h2>Newsletter</h2>
                <p>Stay update with our latest</p>
                <div class="form-element">
                    <input type="text" placeholder="Email"><span><i class="fas fa-chevron-right"></i></span>
                </div>
            </div>
            <div class="instagram" data-aos="fade-left" data-aos-delay="200">
                <h2> Like on Facebook </h2>
                <div class="fb-page" 
  data-href="https://www.facebook.com/facebook"
  data-width="380" 
  data-hide-cover="false"
  data-show-facepile="false"></div>
                <!-- <div class="flex-row">
                    <img src="./assets/instagram/thumb-card3.png" alt="insta1">
                    <img src="./assets/instagram/thumb-card4.png" alt="insta2">
                    <img src="./assets/instagram/thumb-card5.png" alt="insta3">
                </div>
                <div class="flex-row">
                    <img src="./assets/instagram/thumb-card6.png" alt="insta4">
                    <img src="./assets/instagram/thumb-card7.png" alt="insta5">
                    <img src="./assets/instagram/thumb-card8.png" alt="insta6">
                </div> -->
            </div>
            <div class="follow" data-aos="fade-left" data-aos-delay="200">
                <h2>Follow us</h2>
                <p>Let us be Social</p>
                <div>
                    <i class="fab fa-facebook-f"></i>
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-instagram"></i>
                    <i class="fab fa-youtube"></i>
                </div>
            </div>
        </div>
        <div class="rights flex-row">
            <h4 class="text-gray">
                Copyright ©2020 All rights reserved | made by
                <a href="http://answarit.com/" target="_black">Answarit.com 
                    </a>
            </h4>
        </div>
        <div class="move-up">
            <span><i class="fas fa-arrow-circle-up fa-2x"></i></span>
        </div>
    </footer>

    <!-- -------------x------------- Footer --------------------x------------------- -->

     <!-- Jquery Library file -->
     <script src="{% static './js/Jquery3.4.1.min.js' %}"></script>
     <!-- --------- Owl-Carousel js ------------------->
     <script src="{% static './js/owl.carousel.min.js' %}"></script>
     <!-- ------------ AOS js Library  ------------------------- -->
     <script src="{% static './js/aos.js' %}"></script>
     <!-- Custom Javascript file -->
     <script src="{% static './js/main.js' %}"></script>


</body>

</html>

oilblog/templates/index.html
{% extends 'base.html' %}
{% block content %}
    

    <!----------------------------- Main Site Section ------------------------------>

    <main>

        <!-- ---------------------- Site Content -------------------------->

        <section class="container">
            <div class="site-content">
                <div class="posts">
                    {% for obj in object_list %}
                    <div class="post-content" >
                        <div class="post-image">
                            <div>
                                <img src="{{ obj.thumbnail.url }}" class="img" alt="blog1">
                            </div>
                           
                        </div>
                        <div class="post-title">
                            <a href=" {{ obj.get_absolute_url }}"> {{ obj.title }} </a>
                            <p style="text-align:justify">
                                {{ obj.overview|linebreaks|truncatechars:150 }}
                            </p>
                            <button class="btn post-btn"> <a href="{{ obj.get_absolute_url }}"> Read More  </a> &nbsp; <i class="fas fa-arrow-right"></i></button>
                        </div>
                    </div>
                    <hr>
                    {% endfor %}
                    {% if object_list.paginator.num_pages > 1 %}

    <!-- start -->
    {% include '_pagination.html' with items=object_list %}
    <!-- end -->

{% endif %}
                    
                    
                </div>
                <aside class="sidebar">
                    <div class="category">
                        <h2>Category</h2>
                        <ul class="category-list">
                            
                            
                            {% for cat in category %}
                            <li class="list-items" >
                                
                                <a href=" {% url 'post:category' cat.title %} "> {{ cat.title }}</a>
                            <!-- <span>( {{ cat.title__count }} )</span> -->

                            </li>     
                            {% endfor %}
                       
                        </ul>
                    </div>
                    <div class="popular-post">
                        <h2>Recent Post</h2>

                        
                        {% for obj in recent %}
                        <div class="post-content" data-aos="flip-up" data-aos-delay="200">
                            <div class="post-image">
                                <div>
                                    <img src=" {{ obj.thumbnail.url }} " class="img" alt="blog1">
                                </div>
                                <div class="post-info flex-row">
                                    <span><i class="fas fa-calendar-alt text-gray"></i>&nbsp;&nbsp;
                                        {{ obj.timestamp|timesince}}
                                    </span>
                                    <span>2 Comments</span>
                                </div>
                            </div>
                            <div class="post-title">
                                <a href="  ">  {{ obj.title }} </a>
                            </div>
                        </div>
                        {% endfor %}
                            
                       
                        
                    </div>
                    <div class="newsletter" data-aos="fade-up" data-aos-delay="300">
                        <h2>Newsletter</h2>
                        <div class="form-element">
                            <input type="text" class="input-element" placeholder="Email">
                            <button class="btn form-btn">Subscribe</button>
                        </div>
                    </div>
                 
                </aside>
            </div>
        </section>

        <!-- -----------x---------- Site Content -------------x------------>

    </main>

    <!---------------x------------- Main Site Section ---------------x-------------->


{% endblock content %}
    