blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),

    path('tag/<slug:tag_slug>/',views.post_list,name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
            views.post_detail,name='post_detail'),

]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib import admin
from django.urls import re_path,path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls',namespace='blog')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                     document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                     document_root=settings.MEDIA_ROOT)

oilblog/oilblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls',namespace='post'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oilblog/post/urls.py
from django.urls import path
from .views import IndexView,index,PostDetailView,CategoryView
app_name = 'post'

urlpatterns = [
    path('post', IndexView.as_view(), name='index'),
    path('', index, name='index'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('category/<str:cats>/', CategoryView, name='category'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User 
from django.urls import reverse

from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                    self).get_queryset()\
                        .filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published','Published'),
    )
    title    = models.CharField(max_length = 200)
    slug     = models.SlugField(max_length= 200,
                                unique_for_date='publish')
    author   = models.ForeignKey(User,
                                 on_delete=models.CASCADE,
                                 related_name='blog_posts')
    # body     = models.TextField()
    body     = RichTextUploadingField(blank=True, null=True, db_index=True)
    thumbnail= models.ImageField()
    publish  = models.DateField( default =timezone.now)
    # timezone.now method returns current datetime
    created  = models.DateField( auto_now_add=True)
    # auto_now_add will be saved automatically when
    # creating an object
    updated  = models.DateField( auto_now=True)
    # auto_now will be updated automatically when\
    #  saving an obj(showing last updated time)
    status   = models.CharField( max_length=10,
                                choices=STATUS_CHOICES,
                                default='darft')
    # This field shows the status of a psot.You use a chices parameter \
    # so the value of this field can only be set to one of the given choices.
    objects  = models.Manager() # the default manager.
    published= PublishedManager() # Our custom manager.

    tags = TaggableManager()


    class Meta:
        ordering = ('-publish',)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                self.publish.month,
                                                self.publish.day,
                                                self.slug])
    

    def __str__(self):
        return self.title                                                                                                                                                                                                                                                                                                                                             
    

blog/views.py
from django.db.models import Count, Q
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView, DeleteView

from .forms import CommentForm, PostForm
from .models import Post, Author, PostView
from marketing.forms import EmailSignupForm
from marketing.models import Signup

form = EmailSignupForm()


def get_author(user):
    qs = Author.objects.filter(user=user)
    if qs.exists():
        return qs[0]
    return None


class SearchView(View):
    def get(self, request, *args, **kwargs):
        queryset = Post.objects.all()
        query = request.GET.get('q')
        if query:
            queryset = queryset.filter(
                Q(title__icontains=query) |
                Q(overview__icontains=query)
            ).distinct()
        context = {
            'queryset': queryset
        }
        return render(request, 'search_results.html', context)


def search(request):
    queryset = Post.objects.all()
    query = request.GET.get('q')
    if query:
        queryset = queryset.filter(
            Q(title__icontains=query) |
            Q(overview__icontains=query)
        ).distinct()
    context = {
        'queryset': queryset
    }
    return render(request, 'search_results.html', context)


def get_category_count():
    queryset = Post \
        .objects \
        .values('categories__title') \
        .annotate(Count('categories__title'))
    return queryset


class IndexView(View):
    form = EmailSignupForm()

    def get(self, request, *args, **kwargs):
        featured = Post.objects.filter(featured=True)
        latest = Post.objects.order_by('-timestamp')[0:3]
        context = {
            'object_list': featured,
            'latest': latest,
            'form': self.form
        }
        return render(request, 'index.html', context)

    def post(self, request, *args, **kwargs):
        email = request.POST.get("email")
        new_signup = Signup()
        new_signup.email = email
        new_signup.save()
        messages.info(request, "Successfully subscribed")
        return redirect("home")


def index(request):
    featured = Post.objects.filter(featured=True)
    latest = Post.objects.order_by('-timestamp')[0:3]

    if request.method == "POST":
        email = request.POST["email"]
        new_signup = Signup()
        new_signup.email = email
        new_signup.save()

    context = {
        'object_list': featured,
        'latest': latest,
        'form': form
    }
    return render(request, 'index.html', context)


class PostListView(ListView):
    form = EmailSignupForm()
    model = Post
    template_name = 'blog.html'
    context_object_name = 'queryset'
    paginate_by = 1

    def get_context_data(self, **kwargs):
        category_count = get_category_count()
        most_recent = Post.objects.order_by('-timestamp')[:3]
        context = super().get_context_data(**kwargs)
        context['most_recent'] = most_recent
        context['page_request_var'] = "page"
        context['category_count'] = category_count
        context['form'] = self.form
        return context


def post_list(request):
    category_count = get_category_count()
    most_recent = Post.objects.order_by('-timestamp')[:3]
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 4)
    page_request_var = 'page'
    page = request.GET.get(page_request_var)
    try:
        paginated_queryset = paginator.page(page)
    except PageNotAnInteger:
        paginated_queryset = paginator.page(1)
    except EmptyPage:
        paginated_queryset = paginator.page(paginator.num_pages)

    context = {
        'queryset': paginated_queryset,
        'most_recent': most_recent,
        'page_request_var': page_request_var,
        'category_count': category_count,
        'form': form
    }
    return render(request, 'blog.html', context)


class PostDetailView(DetailView):
    model = Post
    template_name = 'post.html'
    context_object_name = 'post'
    form = CommentForm()

    def get_object(self):
        obj = super().get_object()
        if self.request.user.is_authenticated:
            PostView.objects.get_or_create(
                user=self.request.user,
                post=obj
            )
        return obj

    def get_context_data(self, **kwargs):
        category_count = get_category_count()
        most_recent = Post.objects.order_by('-timestamp')[:3]
        context = super().get_context_data(**kwargs)
        context['most_recent'] = most_recent
        context['page_request_var'] = "page"
        context['category_count'] = category_count
        context['form'] = self.form
        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            post = self.get_object()
            form.instance.user = request.user
            form.instance.post = post
            form.save()
            return redirect(reverse("post-detail", kwargs={
                'pk': post.pk
            }))


def post_detail(request, id):
    category_count = get_category_count()
    most_recent = Post.objects.order_by('-timestamp')[:3]
    post = get_object_or_404(Post, id=id)

    if request.user.is_authenticated:
        PostView.objects.get_or_create(user=request.user, post=post)

    form = CommentForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.instance.user = request.user
            form.instance.post = post
            form.save()
            return redirect(reverse("post-detail", kwargs={
                'id': post.pk
            }))
    context = {
        'post': post,
        'most_recent': most_recent,
        'category_count': category_count,
        'form': form
    }
    return render(request, 'post.html', context)


class PostCreateView(CreateView):
    model = Post
    template_name = 'post_create.html'
    form_class = PostForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create'
        return context

    def form_valid(self, form):
        form.instance.author = get_author(self.request.user)
        form.save()
        return redirect(reverse("post-detail", kwargs={
            'pk': form.instance.pk
        }))


def post_create(request):
    title = 'Create'
    form = PostForm(request.POST or None, request.FILES or None)
    author = get_author(request.user)
    if request.method == "POST":
        if form.is_valid():
            form.instance.author = author
            form.save()
            return redirect(reverse("post-detail", kwargs={
                'id': form.instance.id
            }))
    context = {
        'title': title,
        'form': form
    }
    return render(request, "post_create.html", context)


class PostUpdateView(UpdateView):
    model = Post
    template_name = 'post_create.html'
    form_class = PostForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update'
        return context

    def form_valid(self, form):
        form.instance.author = get_author(self.request.user)
        form.save()
        return redirect(reverse("post-detail", kwargs={
            'pk': form.instance.pk
        }))


def post_update(request, id):
    title = 'Update'
    post = get_object_or_404(Post, id=id)
    form = PostForm(
        request.POST or None,
        request.FILES or None,
        instance=post)
    author = get_author(request.user)
    if request.method == "POST":
        if form.is_valid():
            form.instance.author = author
            form.save()
            return redirect(reverse("post-detail", kwargs={
                'id': form.instance.id
            }))
    context = {
        'title': title,
        'form': form
    }
    return render(request, "post_create.html", context)


class PostDeleteView(DeleteView):
    model = Post
    success_url = '/blog'
    template_name = 'post_confirm_delete.html'


def post_delete(request, id):
    post = get_object_or_404(Post, id=id)
    post.delete()
    return redirect(reverse("post-list"))


###########################################################
# from django.db.models import Count
# from django.shortcuts import render,get_object_or_404
# from django.core.paginator import Paginator,EmptyPage,\
#     PageNotAnInteger
# from taggit.models import Tag



# from .models import Post 


# # Create your views here.

# def post_list(request, tag_slug=None):
#     object_list = Post.published.all()
#     recent = Post.objects.order_by('-publish')[0:30]
#     tag = None
#     tags = Post.tags.all()
#     if tag_slug:
#         tag = get_object_or_404(Tag, slug=tag_slug)
#         object_list = object_list.filter(tags__in=[tag])
#     paginator   = Paginator(object_list, 1)
#     page = request.GET.get('page')
#     try:
#         posts = paginator.page(page)
#     except PageNotAnInteger:
#         posts = paginator.page(1)
#     except EmptyPage:
#         posts = paginator.page(paginator.num_pages)
#     return render(request,
#     'blog/post/list.html',
#     {'page':page,
#     'posts': posts,
#     'tag':tag,  
#     'tags':tags,
#     'recent':recent,})

# def post_detail(request, year,month,day,post):
#     post = get_object_or_404(Post,slug=post,
#                                 status='published',
#                                 publish__year=year,
#                                 publish__month=month,
#                                 publish__day=day)
#     post_tags_ids = post.tags.values_list('id', flat=True)
#     similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)

oilblog/post/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,DetailView
from django.shortcuts import (render,
                                get_object_or_404,
                                redirect,
                                reverse,
                                Http404)


from django.core.paginator import Paginator 
from .models import Post, Category, Comment, Author
# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'


def index(request):
    posts = Post.objects.all()
    recent = Post.objects.order_by('-timestamp')[0:30]
    category = Category.objects.all()

    paginator = Paginator(posts, 9)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    
    context = {
        'object_list': posts,
        'recent':recent,
        'category': category,
    }

    return render(request,
                  'index.html',
                  context)

class PostDetailView(DetailView):
    template_name = 'posts/post-detail.html'
    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        instance = Post.objects.get_by_id(pk)
        if instance is None:
            raise Http404("Post doesn't exist")
        return instance

def CategoryView(request, cats):
    
    category_post = Post.objects.filter(categories__title=cats.replace('-',' '))
    context = {"category_post":category_post }
    return render(request, 'posts/category.html', context)

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}|Home {% endblock %}
{% block content %}

<section class="section wb">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-12 col-sm-12 col-xs-12">
                <div class="page-wrapper">
                    <div class="blog-list clearfix">
                        {% for obj in posts %}

                        <div class="blog-box row">
                            <div class="col-md-4">
                                <div class="post-media">
                                    <a  href="{{ obj.get_absolute_url }}" title="">
                                        <img style="width: 15rem; height: 13rem;" src="{{ obj.thumbnail.url }}" alt="" class="w-100 rounded img-fluid">
                                        <div class="hovereffect"></div>
                                    </a>
                                </div><!-- end media -->
                            </div><!-- end col -->

                            <div class="blog-meta big-meta col-md-8">
                                <span class="bg-aqua"><a href="" title=""> Essential Oil</a></span>
                                    
                                    
                                      {% for tag in obj.tags.all %}
                                        <span class="bg-aqua">
                                            <a href="{% url "blog:post_list_by_tag" tag.slug %}" target="_blank">
                                                {{ tag.name }}
                                            
                                            </a>
                                        </span>
                                        {% if not forloop.last %}, {% endif %}
                                     {% endfor %}
                                    
                                <h4><a href="{{ obj.get_absolute_url }}" title=""> {{ obj.title|truncatechars:90 }}</a></h4>
                                <p style="background-color:none;">{{ obj.body|striptags|truncatechars:180 }}</p>
                                <small><a href="  " title=""><i class="fa fa-eye"></i>1289 </a></small>
                                <small><a href="{{ obj.get_absolute_url }}" title=""> {{obj.publish|date:"d F Y" }} </a></small>
                                <small><a href="#" title="">by 
                                {{obj.author}}</a></small> <br>
                                <!-- <button class="btn post-btn rounded text-dark"> <a href="{{ obj.get_absolute_url }}"> Read More </a> 
                                    <i class="fas fa-arrow-right"></i></button> -->
                            </div><!-- end meta -->
                        </div><!-- end blog-box -->

                        <hr class="invis">

                        {% endfor %}

                        <div class="row">
                            <div class="col-lg-10 offset-lg-1">
                                <div class="banner-spot clearfix">
                                    <div class="banner-img">
                                        <img src="upload/banner_05.jpg" alt="" class="img-fluid">
                                    </div><!-- end banner-img -->
                                </div><!-- end banner -->
                            </div><!-- end col -->
                        </div><!-- end row -->

                        <hr class="invis">

                      
                        
                    </div><!-- end blog-list -->
                </div><!-- end page-wrapper -->

                <hr class="invis">
                
                {% include "pagination.html" with page=posts %}
                
            </div><!-- end col -->

            <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12">
                <div class="sidebar">
                    <div class="widget">
                        <h2 class="widget-title">Search</h2>
                        <form class="form-inline search-form">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Search on the site">
                            </div>
                            <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                        </form>
                    </div><!-- end widget -->

                    <div class="widget">
                        <h2 class="widget-title">Recent Posts</h2>
                        <div class="blog-list-widget">
                            <div class="list-group">
                                {% for obj in recent %}
                                <a href="{{ obj.get_absolute_url }}" class="list-group-item list-group-item-action flex-column align-items-start">
                                    <div class="w-100 justify-content-between">
                                        <img style="width: 4.5rem;height:4rem;" src="{{ obj.thumbnail.url }}" alt="" class="img-fluid float-left">
                                        <h5 class="mb-1"> {{ obj.title|truncatechars:60 }}  </h5> 
                                        <small>{{ obj.publish}}</small>
                                    </div>
                                </a>
                                {% endfor %}
                            </div>
                        </div><!-- end blog-list -->
                    </div><!-- end widget -->

                    <div class="widget">
                        <h2 class="widget-title">Advertising</h2>
                        <div class="banner-spot clearfix">
                            <div class="banner-img">
                                <img src="upload/banner_04.jpg" alt="" class="img-fluid">
                            </div><!-- end banner-img -->
                        </div><!-- end banner -->
                    </div><!-- end widget -->

                    <div class="widget">
                        <h2 class="widget-title">Instagram Feed</h2>
                        <div class="instagram-wrapper clearfix">
                            <a href="#"><img src="upload/garden_sq_01.jpg" alt="" class="img-fluid"></a>
                            <a href="#"><img src="upload/garden_sq_02.jpg" alt="" class="img-fluid"></a>
                            <a href="#"><img src="upload/garden_sq_03.jpg" alt="" class="img-fluid"></a>
                            <a href="#"><img src="upload/garden_sq_04.jpg" alt="" class="img-fluid"></a>
                            <a href="#"><img src="upload/garden_sq_05.jpg" alt="" class="img-fluid"></a>
                            <a href="#"><img src="upload/garden_sq_06.jpg" alt="" class="img-fluid"></a>
                            <a href="#"><img src="upload/garden_sq_07.jpg" alt="" class="img-fluid"></a>
                            <a href="#"><img src="upload/garden_sq_08.jpg" alt="" class="img-fluid"></a>
                            <a href="#"><img src="upload/garden_sq_09.jpg" alt="" class="img-fluid"></a>
                        </div><!-- end Instagram wrapper -->
                    </div><!-- end widget -->

                    <div class="widget">
                        <h2 class="widget-title">Popular Categories</h2>
                        <div class="link-widget">
                            <ul>
                                {% for tag in tags %}
                                <li>
                                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}
                                    <span>(21)</span>
                                    </a>
                                </li>
                                {% endfor %}
                                <li><a href="#">Outdoor Living <span>(15)</span></a></li>
                                <li><a href="#">Indoor Living <span>(31)</span></a></li>
                                <li><a href="#">Shopping Guides <span>(22)</span></a></li>
                                <li><a href="#">Pool Design <span>(66)</span></a></li>
                            </ul>
                        </div><!-- end link-widget -->
                    </div><!-- end widget -->
                </div><!-- end sidebar -->
            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end container -->
</section>






{% endblock %}